version: "3.7"
services:
    db:
        image: mysql:latest
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=fitnessdb
        restart: always

    api:
        build:
            context: './api'
        container_name: api
        ports:
            - '8080:8080'
        depends_on:
            - 'db'