version: "3.7"
services:
    db:
        image: mysql:latest
        container_name: db
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        restart: always
        networks:
            - appNetwork

    api:
        build:
            context: './api'
        container_name: api
        ports:
            - '8080:8080'
        depends_on:
            - 'db'
        networks:
            - appNetwork

networks:
    appNetwork:
        driver: "bridge"